// <auto-generated />
using Data.SDK;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProcessImage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251018150711_UpdateBuilder")]
    partial class UpdateBuilder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProcessImage.Domain.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DimensiuneMaximaMb")
                        .HasColumnType("int");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SubscriptieProcesareID")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Pret")
                        .HasDatabaseName("IX_Subscriptie_Pret");

                    b.HasIndex("SubscriptieProcesareID")
                        .HasDatabaseName("IX_Subscriptie_ProcesareID");

                    b.HasIndex("Tip")
                        .HasDatabaseName("IX_Subscriptie_Tip");

                    b.ToTable("Subscription", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
