// <auto-generated />
using System;
using Data.SDK;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProcessImage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251025101039_AddNewDatainSubscription")]
    partial class AddNewDatainSubscription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProcessImage.Domain.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DimensiuneMaximaMb")
                        .HasColumnType("int");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SubscriptieProcesareID")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Pret")
                        .HasDatabaseName("IX_Subscriptie_Pret");

                    b.HasIndex("SubscriptieProcesareID")
                        .HasDatabaseName("IX_Subscriptie_ProcesareID");

                    b.HasIndex("Tip")
                        .HasDatabaseName("IX_Subscriptie_Tip");

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("ProcessImage.Entities.Imagine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CaleFisier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DataIncarcarii")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UtilizatorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Nume")
                        .HasDatabaseName("IX_Imagini_Nume");

                    b.HasIndex("UtilizatorId")
                        .HasDatabaseName("IX_Imagini_UtilizatorId");

                    b.ToTable("Imagini", (string)null);
                });

            modelBuilder.Entity("ProcessImage.Entities.ProcesareImagine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataProcesare")
                        .HasColumnType("datetime2");

                    b.Property<long>("ImagineId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("TipProcesareId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ImagineId")
                        .HasDatabaseName("IX_ProceseImagini_ImagineId");

                    b.HasIndex("TipProcesareId")
                        .HasDatabaseName("IX_ProceseImagini_TipProcesareId");

                    b.ToTable("ProceseImagini", (string)null);
                });

            modelBuilder.Entity("ProcessImage.Entities.SubscripteProcesare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("LimitaMax")
                        .HasColumnType("int");

                    b.Property<long>("SubscriptieId")
                        .HasColumnType("bigint");

                    b.Property<long>("TipProcesareId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptieId")
                        .HasDatabaseName("IX_SubscripteProcesare_SubscriptieId");

                    b.HasIndex("TipProcesareId")
                        .HasDatabaseName("IX_SubscripteProcesare_TipProcesareId");

                    b.ToTable("SubscripteProcesare", (string)null);
                });

            modelBuilder.Entity("ProcessImage.Entities.Subscriptie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("DimensiuneMaximaMb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SubscriptieProcesareId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subscriptie");
                });

            modelBuilder.Entity("ProcessImage.Entities.TipProcesare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nume")
                        .HasDatabaseName("IX_TipProcesare_Nume");

                    b.ToTable("TipProcesare", (string)null);
                });

            modelBuilder.Entity("ProcessImage.Entities.Utilizator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SubscriptieId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptieId");

                    b.ToTable("Utilizator");
                });

            modelBuilder.Entity("ProcessImage.Entities.Imagine", b =>
                {
                    b.HasOne("ProcessImage.Entities.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("ProcessImage.Entities.ProcesareImagine", b =>
                {
                    b.HasOne("ProcessImage.Entities.Imagine", "Imagine")
                        .WithMany()
                        .HasForeignKey("ImagineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessImage.Entities.TipProcesare", "TipProcesare")
                        .WithMany()
                        .HasForeignKey("TipProcesareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imagine");

                    b.Navigation("TipProcesare");
                });

            modelBuilder.Entity("ProcessImage.Entities.SubscripteProcesare", b =>
                {
                    b.HasOne("ProcessImage.Entities.Subscriptie", "Subscriptie")
                        .WithMany("SubscripteProcesares")
                        .HasForeignKey("SubscriptieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessImage.Entities.TipProcesare", "TipProcesare")
                        .WithMany("SubscripteProcesares")
                        .HasForeignKey("TipProcesareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subscriptie");

                    b.Navigation("TipProcesare");
                });

            modelBuilder.Entity("ProcessImage.Entities.Utilizator", b =>
                {
                    b.HasOne("ProcessImage.Entities.Subscriptie", "Subscriptie")
                        .WithMany("Utilizators")
                        .HasForeignKey("SubscriptieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscriptie");
                });

            modelBuilder.Entity("ProcessImage.Entities.Subscriptie", b =>
                {
                    b.Navigation("SubscripteProcesares");

                    b.Navigation("Utilizators");
                });

            modelBuilder.Entity("ProcessImage.Entities.TipProcesare", b =>
                {
                    b.Navigation("SubscripteProcesares");
                });
#pragma warning restore 612, 618
        }
    }
}
